### PR TITLE
Bind all callbacks as instance methods.

### PR DESCRIPTION
**Pull request by fquinto**
Similar idea from @yoch in #63 and some visual corrections

### CODE REVIEW

**Comment by PierreF** [comment]
Tests are failing because this PR break callbacks (at least when not using subclass).
The following usage is what makes test fail:
```
def on_connect(mqtt_client, userdata, flags, rc):
    pass

mqtt_client.on_connect = on_connect
```

The callback is called with userdata, flag and rc but is missing mqtt_client first parameter.

**Comment by swails** [comment]
Changes were made awhile ago to support subclassing `Client` that required a fair bit of weirdo Python magic to support more traditional subclassing behavior without breaking backwards compatibility.

What I realized doing that is that what is being attempted here is, quite simply, impossible to do while retaining backwards compatibility.

Since the API indicates that you should attach callbacks via assignment to *instances* (rather than the class definition itself), the callbacks *can't* be treated like an instance method (i.e., one in which the first argument is passed automatically as is typical for `self`).  If you can't treat these callbacks as instance methods, the only way to make the parent `Client` instance visible to callbacks in general is to leave them accepting a `client` argument that is redundant with `self` in the cases where those callbacks are instance methods.

While I like the feel of this API better, the churn it will impose on consumers of this client library that will be required to refactor to continue to use paho is significant and not worth the largely cosmetic API improvements IMO.

**Comment by fquinto** [comment]
I don't have checked yet in deeply in order to say now that the compatibility backwards it's impossible. Maybe with "ugly and redundant" code can we get it? I understand the backward compatibility it's necessary but I need this subclass at the same time. Any specific proposal to support both needs?

**Comment by swails** [comment]
> I understand the backward compatibility it's necessary but I need this subclass at the same time. Any specific proposal to support both needs?

Subclassing already works.  You just need to make sure that instance method callbacks have a redundant `client` argument which just gets ignored:

```python
class ClientSubclass(Client):

    def on_connect(self, _, userdata, flags, rc):
        # Your code goes here
```

Note you need paho 1.3.0 for this (overriding callbacks in subclasses did not work in earlier versions).

**Comment by swails** [comment]
> I don't have checked yet in deeply in order to say now that the compatibility backwards it's impossible. Maybe with "ugly and redundant" code can we get it?

The only way you can maintain backwards compatibility is to change the places where the callbacks are called and use Python's introspection capabilities to look at how many arguments the method takes and whether it's an instance method or not, then based on the set of supported usage patterns use the appropriate call signature.

But this is beyond ugly -- it's confusing and rife with possible corner cases.  I can think of no other way of supporting both instance methods *and* non-instance methods in the same API.

**Comment by fquinto** [comment]
Therefore... how to continue now? Implementation with _introspection capabilities in Python and counting how many arguments the method takes_ proposal, past the Travis test and accepting this _pull request_ or close this pull request? What do you think about that?

Clarification note: for me _ugly_ = look at how many arguments the method takes

**Comment by swails** [comment]
My understanding is that the current implementation allows you to define instance methods for the callbacks in a subclass of `Client`, but requires you to accept a dummy `Client` instance redundant with `self` to support the original API that consisted of assigning callback functions to instances.

Basically what that means is that you need to change the call signature of your overriding callbacks from:

```python
class MyClient(Client):
    # This is "cleaner"
    def on_connect(self, userdata, flags, rc):
        <your code>
```

to:

```python
class MyClient(Client):
    # This isn't as "clean"
    def on_connect(self, _, userdata, flags, rc):
        <your code>
```

Unless I'm missing something and there's something else the changes proposed here allows that is otherwise harder to do, my suggestion is to close this PR and #63.

**Comment by fquinto** [comment]
Thanks for your comments.

**Pull request closed without merging**
