### PR TITLE
use same format in logs (missed line)

### PR DESCRIPTION
**Pull request by yoch**
Signed-off-by: yoch <yoch.melka@gmail.com>

### CODE REVIEW

**Comment by yoch** [comment]
Continues #76 (sorry for that)

**Comment by ralight** [comment]
Just to say, keep the requests coming. I'm not ignoring them, just having to work on other things at the moment.

Also, do you realise you can do a force push against the branch with your other pull request in and it should be updated.

**Comment by yoch** [comment]
I do a simple commit and push in [my branch](https://github.com/yoch/paho.mqtt.python/commits/debug2), but the PR hasn't been updated, and I had a link for creating a new PR instead.

**Comment by ralight** [comment]
Oh ok, I thought it should work.

**Comment by Nzbuu** [comment]
The original PR #76 has already been merged, I think

**Comment by ralight** [comment]
That'll be why then, I didn't look properly :)

**Comment by Nzbuu** [comment]
I think this is fixed in https://github.com/eclipse/paho.mqtt.python/pull/95 now.

**Comment by ralight** [comment]
I'm closing this because I believe it is fixed already, thanks for your contribution.

**Pull request closed without merging**
