### PR TITLE
Travis CI: Add Python 3.7 and 3.8 to testing

### PR DESCRIPTION
**Pull request by cclauss**
#317 redone in a way that will not confuse the __eclipsefdn/eca__ bot.

Signed-off-by: cclauss <cclauss@me.com>

### CODE REVIEW

**Comment by cclauss** [comment]
Closing because the __eclipsefdn/eca__ bot is really, really broken!!

**Comment by CAM-Gerlach** [comment]
Is that why there seem to be more closed than merged PRs on this repo? I've never seen any major project that actually accepts PRs have this many closed ones...crazy.

**Comment by swails** [comment]
Many pull requests don't get merged directly. Maintainers will incorporate changes and merge a different PR, then close the original.

**Comment by CAM-Gerlach** [comment]
Hmm I see; when I was a core dev with Spyder, a relatively large (~5k stars, 20k commits) community-developed project, we would usually require changes, sometimes minor and sometimes drastic, but would always give the contributor a chance to make them first; only infrequently did we need to work on the PR branch ourselves in cases where the user abandoned it or indicated they weren't able to make the requested changes, and even more rare was the need to create a separate PR branch for whatever reason. But I suppose this project has very different requirements as a backend library as opposed to a user-facing scientific IDE, and with development lead by an organization with CLAs and whatnot rather than the community.

**Pull request closed without merging**
