### PR TITLE
Make Travis tests run on `fixes` branch

### PR DESCRIPTION
**Pull request by Nzbuu**
* Cherry-pick pull requests #93, #159 and #161 from `develop` branch
* Fix unicode test case on Python 3.2

### CODE REVIEW

**Comment by Nzbuu** [comment]
@ralight , @PierreF , Do you think this can be merged?

**Comment by PierreF** [comment]
It's Quiet big diff :). I won't have time to look at this this week. I'll try to look this PR and other one this week-end or early next week.

**Comment by Nzbuu** [comment]
Thanks @pierref.

Hopefully it's not actually as big as it seems. I've just cherry-picked 3 pull requests from the develop branch and made some minor tweaks for the differences between the branches and to fix the unicode test on python 3.2.

**Comment by Nzbuu** [comment]
Thanks :)

**Pull request merged**
