### PR TITLE
Use f-strings where sensible

### PR DESCRIPTION
**Pull request by akx**
This PR replaces various string formatting operations with Python 3.6+ f-strings, for performance and brevity.

Guided by [Flynt](https://github.com/ikamensh/flynt/) and Ruff's relevant lints, checked by hand.

### CODE REVIEW

**Comment by cclauss** [comment]
Do ruff [`EM` rules](https://docs.astral.sh/ruff/rules/#flake8-errmsg-em) object to some of these uses?

**Comment by akx** [comment]
@cclauss Not any more than they would with other formatting. I don't really agree with the `EM` rules because they make the code longer and more cumbersome to read. Henry's point [is](https://pypi.org/project/flake8-errmsg/)

> If this is longer or more complex, the duplication can be quite confusing for a user unaccustomed to reading tracebacks.

and I would assume people who use MQTT should be accustomed to reading tracebacks.

**Review by PierreF — APPROVED** [review]

**Comment by cclauss** [comment]
@akx git conflicts here.

**Comment by akx** [comment]
@cclauss Thanks, rebased.

**Pull request merged**
