### PR TITLE
fixed the rc parameter MQTT_ERR_CONN_LOST to be passed instead of 1 t…

### PR DESCRIPTION
**Pull request by nawab36085**
…o user callback function on_disonncect

### CODE REVIEW

**Comment by denravonska** [comment]
Is there a reason why this is still open, or why there has been no reaction to it for 4 months?

**Comment by karlp** [comment]
The documentation states that it's "0 for explicit disconnect, non-zero for unexpected disconnect"  you're not _meant_ to be trying to decode it further.

**Comment by denravonska** [comment]
> The documentation states that it's "0 for explicit disconnect, non-zero for unexpected disconnect" you're not _meant_ to be trying to decode it further.

In that case I'd argue that both the documentation and the implementation are wrong.

**Comment by karlp** [comment]
The documentation matches the implementation.  Should the implementation be made more like other functions where rc _can_ be decoded with mosq_errstr()?  sure, that sounds perfectly reasonable, but that's an enhancement.

**Comment by denravonska** [comment]
Depending on if it's a conscious decision or not you can view it as either a bug or a change request. Either way, it would be handy if the return codes are used consistently, especially when the function in question does use the provided define for positive outcomes.

**Comment by ralight** [comment]
This is now fixed - I've done it in a slightly different and more comprehensive way than this PR, so I'm going to close this. Thanks for the request.

**Pull request closed without merging**
