### PR TITLE
Added support of password protected private keys for client authentication

### PR DESCRIPTION
**Pull request by tzahari**
Now you can use password protected client keys.

### CODE REVIEW

**Comment by tzahari** [comment]
Is someone is willing to takeover? I do not want to register myself for 2 lines of code changes.

**Comment by ralight** [comment]
I've implemented this and added a test, thanks very much for the suggestion and PR!

**Comment by tzahari** [comment]
Hi @ralight , 
Thank you to implement this. 
Is there an ETA for a release with this changes?
Best Regards Thomas

**Comment by ralight** [comment]
Not at the moment - I want to go through the issues first and I don't know
how long that will take.

**Pull request closed without merging**
