### PR TITLE
Enable more Ruff rules (incl. those `ignore`d previously)

### PR DESCRIPTION
**Pull request by akx**

### CODE REVIEW

**Comment by akx** [comment]
🔔 @cclauss 😁

**Comment by PierreF** [comment]
I think there will be a conflict between this PR and #776 . #776 is currently mergeable (no conflict), so it should probably be better to merge #776 first. @akx, you were asked for a review on that PR that why I wait to merge it.

**Comment by akx** [comment]
Draft for the time being – #776 reorganized pyproject.toml in a way that caused rather annoying conflicts so I'll re-check things once more.

**Comment by akx** [comment]
@PierreF Rebased, ready for review.

**Comment by PierreF** [comment]
Thank ! That's a good cleanup

**Pull request merged**
