### PR TITLE
Run tests with coverage reporting

### LINKED ISSUE #775: CI: enable code coverage tracking
[Codecov](https://about.codecov.io/) has a handy GitHub Action and a free tier for OSS projects.

### PR DESCRIPTION
**Pull request by akx**
Fixes #775.

### CODE REVIEW

**Comment by akx** [comment]
Things seem to work: https://app.codecov.io/github/eclipse/paho.mqtt.python/pull/782/tree

@PierreF Would you like me to see if we can get the coverage% as a GitHub comment without an external service?

If we want Codecov to comment on the PRs, someone admin enough on `eclipse` will need to enable this repo on https://app.codecov.io/ .

**Review by PierreF — APPROVED** [review]

**Comment by PierreF** [comment]
I think codecov could be fine, it seems already used by few other project from Eclipse.

@akx did you know which "admin enough" right are needed ? @icraggs do you know who to ask for (if not you).

**Comment by akx** [comment]
@PierreF Presumably someone who can see `eclipse` on https://github.com/apps/codecov/installations/select_target :)

**Comment by icraggs** [comment]
Ok, I think I've done everything needed. Let me know if not.

**Comment by PierreF** [comment]
@akx I've re-run one of the tox job. Should we expect something on this PR or should I merge it and we should see it on future PR ?

**Comment by akx** [comment]
@PierreF I think hopefully we'll see Codecov comment in a subsequent PR after this gets merged :) Thanks!

**Pull request merged**
