### PR TITLE
fix for #73

### PR DESCRIPTION
**Pull request by yoch**
fix for #73

### CODE REVIEW

**Comment by yoch** [comment]
I doubt if the default behavior should be to generate a random client_id or use a empty client_id. But current behavior (mixing the two concepts) seems incorrect.

**Comment by ralight** [comment]
The point with generating an id rather than using None is that it works
with both 3.1 and 3.1.1.

I like the uuid approach, but there is no need to truncate to 23 characters
these days.

**Comment by yoch** [comment]
I'm not familiar with the 3.1 version. But forcing users to use client_id random, even if he wants a null one, may be problematic. So this PR seems to be the right approach.

Reason to limit to 23 characters is to be as compatible as possible : 

> The Server **MUST** allow ClientIds which are between 1 and 23 UTF-8 encoded bytes in length, and that contain only the characters
> "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" [MQTT-3.1.3-5].
>  
> The Server **MAY** allow ClientId’s that contain more than 23 encoded bytes. The Server MAY allow ClientId’s that contain characters not included in the list given above.

**Comment by michaelplaing** [comment]
uuid's are 128 bits and can be compacted to fit in 23 text bytes.

I suspect that is where that limit came from.

**Comment by michaelplaing** [comment]
i.e. using base 62.

(this is as I recall from a test some years ago)

**Comment by michaelplaing** [comment]
we import 'numconv' to assist with base 62 conversions, which we use for
another purpose.

**Comment by yoch** [comment]
@michaelplaing 
- 128 bits can be encoded in 22 alphanumeric characters in base 62 : *ceil((128 * log(2)) / log(62))*
- this can be added easyly if necessary (thus avoiding dependencies)

```python
import string 
import uuid

def base62(num, base=string.digits+string.ascii_letters, padding=1):
	assert num >= 0
	digits = []
	while num:
		num, rest = divmod(num, 62)
		digits.append(base[rest])
	digits.extend(base[0] for _ in range(len(digits), padding))
	return ''.join(reversed(digits))

base62(uuid.uuid4().int, padding=22)
```

**Comment by ralight** [comment]
That looks good to me, feel free to add it to the current request.

I'm told the 23 character limit is down to a field in WebSphere MQ being limited to 24 characters - so 23 characters plus a zero terminator.

**Comment by michaelplaing** [comment]
Thanks for the history, Roger!

**Comment by ralight** [comment]
If you update this pull request to just include the uuid changes I'll accept it.

If clean session is set to False and the user does not provide a client id, they have no way of knowing what the client id is (ok, so they could look inside their client instance for the random id, but it's hardly good behaviour) and so they are creating a durable client that can never be resumed. This is not good.

**Comment by yoch** [comment]
I agree. But it's still possible to allow null client id with clean session, right ?

**Comment by ralight** [comment]
"With clean session" means "clean_session=True" to me. In that case you can do what you want. If clean_session is False, the client id cannot be zero length going to the broker, and the library intentionally prevents you from doing that if has generated a random id for you.

**Comment by ralight** [comment]
Sorry I wasn't clear, could you scrub the rest of the history (i.e. a force push without the other commits) - this only needs to be a single commit. Let's keep things tidy :)

**Comment by yoch** [comment]
done

**Pull request merged**
