### PR TITLE
Return correct object as client protocol

### LINKED ISSUE #820: Reading Client protocol property causes infinite recursion loop
# Bug Description

Accessing the field `Client.protocol` causes infinite recursion, since there is a bug in how that property is defined. The bug is on [this line](https://github.com/eclipse/paho.mqtt.python/blob/613520775c5706f72b916a99a8931983633fe489/src/paho/mqtt/client.py#L956). The function should return `self._protocol` and not `self.protocol` as the latter is a recursive definition.
This is the property.
```python
    @property
    def protocol(self) -> MQTTProtocolVersion:
        """
        Protocol version used (MQTT v3, MQTT v3.11, MQTTv5)

        This property is read-only.
        """
        return self.protocol
```

### PR DESCRIPTION
**Pull request by asikeero**
Fixes #820

### CODE REVIEW

**Comment by PierreF** [comment]
Thanks for catching this error. Could you sign ECA (https://accounts.eclipse.org/user/eca / https://www.eclipse.org/legal/ECA.php) so I can merge you PR ?

**Comment by asikeero** [comment]
Done, should be OK now.

**Comment by asikeero** [comment]
Two checks are failing due to reasons that seem not to relate to this PR. Just to clarify, am I expected to add something to this PR to make them pass?

**Comment by PierreF** [comment]
Thanks for your patience. Pytest (tox) tend to be have false-positive errors (cf #789). The lint_python error is a real error, linked to your change.
Your change isn't the issue actually, but make the issue visible: `self._protocol` is not correctly typed.

I'll merge your PR and fix the typing once merged.

Thanks for your contribution.

**Pull request merged**
