### PR TITLE
Replace _out_packet list by collections.deque

### PR DESCRIPTION
**Pull request by robertobarreda**
- deque provides higher perfomance popping from left end of the list

### CODE REVIEW

**Comment by ralight** [comment]
I've got conflicting pull requests #64 and #69. I think either is better than the current code, but can we discuss which is best?

**Comment by robertobarreda** [comment]
@ralight I think both #64 and #69 changes are compatible:
- #69 changes _out_messages and _in_messages
- #64 changes _out_packet

You can merge one of the pull requests and then we can fix the other one based on the last version of the code.

**Comment by yoch** [comment]
@ralight, @robertobarreda yes, these PR are fully compatible with #69, because #64 apply to `_out_packet` and #69 to `_out_messages` and `_in_messages`.

**Comment by karlp** [comment]
Same issue applies to publish.multiple, only there it still misses the pop(0) to publish in the order of the original list

**Comment by Nzbuu** [comment]
I think the target branch for this pull request should be "develop" not "master"

**Comment by ralight** [comment]
This looks fine, but the ip validation checks are not passing. Please sign the Eclipse ECA with the email that you use for your commits. There are some commits that have a different email address of robertobarreda@users.noreply.github.com which I assume it's actually yours... Please also add a signed-off-by line to your commit (use "git commit -s").

Finally, as you've got to redo the commits anyway could you try and make it without the extra merges and existing commits.

Thanks for your patience!

**Comment by robertobarreda** [comment]
@ralight I've created a new pull-request #116 to properly merge with develop branch and fix the signed-off-by issue. I'm closing this issue.

**Pull request closed without merging**
