### PR TITLE
extended MQTTMessageInfo:wait_for_publish with a timeout

### PR DESCRIPTION
**Pull request by nickma82**
In order to enable waiting with timeout after issuing
  mqtt.Client's publish(..) like:

```
infot = self.mqttc.publish(topic, msg, qos=1)
infot.wait_for_publish(0.5)
```

### CODE REVIEW

**Comment by nickma82** [comment]
How to obtain the "necessary legal agreements"?
I went to accounts.eclipse.org (completing like 15 reCaptchas) which seems like a dead end... O_o

**Comment by ralight** [comment]
Hi @nickma82, if you're still interested in doing this then you should go to https://www.eclipse.org/legal/ECA.php and use the ECA form link near the top. You should use the same email address as is used in your commit message.

I'd be keen to have you do that, this is a good addition and implemented in a nice way.

**Comment by hildogjr** [comment]
@nickma82 you have to do your commit with the (pseudo) e-mail used by GitHub.
Check the page https://github.com/settings/emails, you will find a `???@users.noreply.github.com `, so do:

```bash
git config --global user.name YOURNAME
git config --global user.email THEEMAILABOVE
```

After, do the same commits on a new branch.

**Comment by nickma82** [comment]
Thanks, registering at ECA@eclipse did the trick.

**Comment by nickma82** [comment]
@ralight all done.

**Comment by ralight** [comment]
I've merged this in https://github.com/eclipse/paho.mqtt.python/commit/7f40ca9a64c427ede2eff200f1ce266e164028d9 - I'm not sure why the PR on github hasn't been closed as merged though. Oh well! Thanks again @nickma82

**Pull request closed without merging**
