### PR TITLE
update setup.py to use setuptools and fall back to distutils when unavailable

### PR DESCRIPTION
**Pull request by fmoor**
also removed tab characters and replaced them with spaces, because tabs do not render the same in all editors.

### CODE REVIEW

**Comment by fmoor** [comment]
It looks like the travis script is broken...

**Comment by ralight** [comment]
Thanks for this, but the same changes have already been made in the develop branch.

**Comment by fmoor** [comment]
I guess I should have started there...

**Comment by ralight** [comment]
:)

Even if you had, I only merged it the other day so there may well have been an overlap.

**Pull request closed without merging**
