### PR TITLE
Update trio example to work with latest trio

### LINKED ISSUE #678: Trio example not working with latest trio version
Hi,

I am trying to run paho with trio.

I am completely new to paho or trio.

I got a copy paste of the example.

I am using:

* Python 3.10.4  - Ubuntu 22.04
* trio (0.21.0)
* paho (1.6.1)

The traceback

```
python run-trio.py 
Starting
Socket opened
large write request
misc_loop started
Traceback (most recent call last):
  File "/home/adi/chevah/run-trio.py", line 139, in <module>
    trio.run(TrioAsyncMqttExample().main)
  File "/home/adi/chevah/venv/lib/python3.10/site-packages/trio/_core/_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "/home/adi/chevah/run-trio.py", line 129, in main
    async with trio.open_nursery() as nursery:
  File "/home/adi/chevah/venv/lib/python3.10/site-packages/trio/_core/_run.py", line 813, in __aexit__
    raise combined_error_from_nursery
  File "/home/adi/chevah/run-trio.py", line 70, in read_loop
    await trio.hazmat.wait_readable(self.sock)
  File "/home/adi/chevah/venv/lib/python3.10/site-packages/trio/_deprecate.py", line 124, in __getattr__
    raise AttributeError(msg.format(self.__name__, name))
AttributeError: module 'trio' has no attribute 'hazmat'
finished large write
```

It looks like the hazmat was deprecated https://github.com/python-trio/trio/pull/1722

### PR DESCRIPTION
**Pull request by adiroiban**
Fixes #678 

I am just updating the usage of the now deprecated and removed `trio.hazmat`

### CODE REVIEW

**Comment by PierreF** [comment]
Hello and thank for this fix. Could you sign the ECA (https://www.eclipse.org/legal/ECA.php) which is required to accept your contribution ?

**Comment by PierreF** [comment]
The ECA validation tools don't find you email address in its database. Did you completed the form with another email address ?

**Comment by adiroiban** [comment]
Not sure what to do. In the eclipse page I see 
image

**Comment by PierreF** [comment]
Check is now good. Maybe their had some lag in processing. Anyway it's good now. Thanks!

**Pull request merged**
