### PR TITLE
Updated documentation: max message queue size

### PR DESCRIPTION
**Pull request by JsBergbau**
I've also stumbled upon the max message queue size of 65555, see https://github.com/eclipse/paho.mqtt.python/issues/377
So unless this is fixed documentation should tell about that fact. Knowing this can save a lot of time, hassles and headache.

### CODE REVIEW

**Comment by yschroeder** [comment]
Maybe you want to clarify that this is indeed 65555 and not 65535 with a typo?

Something like:

`Defaults to 0. 0 means unlimited, but due to implementation currently limited to 65555 (65535 messages in queue + 20 messages in flight). When the queue is full, any further outgoing messages would be dropped.`

**Comment by JsBergbau** [comment]
Thanks for the hint. Documentation is updated. Hopefully this pull request is merged soon.

**Comment by JsBergbau** [comment]
This is just a minor documentation fix, however it is still not merged. What is else required that it can be merged?

**Comment by ralight** [comment]
Thank you, and sorry for not getting to this earlier.

**Pull request merged**
