### PR TITLE
Add proxy support for 'single' and 'multiple' operations

### PR DESCRIPTION
**Pull request by antechrestos**
This change attempts to solve issue  #402

### CODE REVIEW

**Comment by antechrestos** [comment]
I don't know why tests are failing due to a missing `six` import

**Comment by antechrestos** [comment]
After some investigation, it seems that the pipeline is broken for python 3.5 and 3.6 as six is not installed anymore by tox for these python versions...

**Comment by PierreF** [comment]
The travis error is like to be the same that the one i've fixed in commit c3c8598 (cf https://github.com/eclipse/paho.mqtt.python/pull/334#issuecomment-512695890).
Tox is ok on local, i'm merging and travis will re-check on master with commit c3c8598 included.

Thank for your contribution.

**Comment by antechrestos** [comment]
Thank you.

**Pull request merged**
